#!/usr/bin/env ruby
# frozen_string_literal: true

# Writes one Dockerfile per entry in Parsers::COMBOS.
#
# One file per combination rather than one parameterised file, because a
# Dockerfile in the tree is a readable record of what an image contains -- and
# because docker build --build-arg leaves no trace in the built image, so an
# image built from ARGs cannot be traced back to the arguments that made it.
#
# Run after editing COMBOS:
#
#   ruby docker/psych_matrix/generate.rb
#
# It rewrites every file it manages and leaves nothing else alone, so a removed
# combo leaves a stale Dockerfile behind; it prints those rather than deleting
# generated-looking files on its own.

$LOAD_PATH.unshift(File.expand_path('../../lib', __dir__))
require 'parsers'

HERE = __dir__

def dockerfile(combo)
  ruby     = combo[:ruby]
  suite    = combo[:suite] || 'bookworm'
  libyaml  = combo[:libyaml]
  psych    = combo[:psych]

  <<~DOCKER
    # GENERATED by docker/psych_matrix/generate.rb -- edit COMBOS in
    # lib/parsers.rb and re-run that script instead of editing this file.
    #
    # ruby #{ruby} / psych #{psych} / libyaml #{libyaml}
    #
    # #{combo[:note]}

    FROM ruby:#{ruby}-#{suite}

    RUN apt-get update && apt-get install -y --no-install-recommends \\
          build-essential autoconf automake libtool pkg-config git ca-certificates \\
        && rm -rf /var/lib/apt/lists/*

    # libyaml from its git tag rather than a release tarball: the tarball naming
    # changed across the 0.2.x series and some tags have no tarball at all, so
    # the tag is the only identifier that works for every version here.
    RUN git clone --depth 1 --branch #{libyaml} https://github.com/yaml/libyaml.git /tmp/libyaml \\
        && cd /tmp/libyaml \\
        && ./bootstrap \\
        && ./configure --prefix=/usr/local \\
        && make -j"$(nproc)" \\
        && make install \\
        && ldconfig \\
        && rm -rf /tmp/libyaml

    RUN gem install psych -v #{psych} -- --with-libyaml-dir=/usr/local

    # Ruby ships its own psych as a default gem, and a default gem wins over an
    # installed one for a plain `require "yaml"` when the installed version is
    # older. Overwriting the copy on the load path is what makes the pin hold in
    # both directions -- without this, every downgrade row would silently report
    # the version Ruby bundles.
    RUN set -e; \\
        gemdir="$(ruby -e 'print Gem.dir')/gems/psych-#{psych}"; \\
        rubylibdir="$(ruby -e 'print RbConfig::CONFIG["rubylibdir"]')"; \\
        archdir="$(ruby -e 'print RbConfig::CONFIG["archdir"]')"; \\
        rm -rf "$rubylibdir/psych" "$rubylibdir/psych.rb"; \\
        cp -r "$gemdir/lib/psych.rb" "$gemdir/lib/psych" "$rubylibdir/"; \\
        cp "$(find "$(ruby -e 'print Gem.dir')/extensions" -name psych.so | head -1)" "$archdir/psych.so"

    # Fail at build time rather than mislabelling every result from this image.
    # Psych::VERSION proves which Ruby code loaded and LIBYAML_VERSION which C
    # library it is bound to, which together are the whole identity of the row.
    RUN ruby -ryaml -e 'abort "got psych #{'#{Psych::VERSION}'}, wanted #{psych}" unless Psych::VERSION == "#{psych}"' \\
     && ruby -ryaml -e 'abort "got libyaml #{'#{Psych::LIBYAML_VERSION}'}, wanted #{libyaml}" unless Psych::LIBYAML_VERSION == "#{libyaml.sub(/-rc.*/, '')}"' \\
     && ruby -ryaml -e 'raise "sanity check failed" unless YAML.load("a: 1") == {"a" => 1}' \\
     && ruby -ryaml -e 'warn "psych #{'#{Psych::VERSION}'} / libyaml #{'#{Psych::LIBYAML_VERSION}'} / ruby #{'#{RUBY_VERSION}'}"'

    COPY emit.rb /emit.rb

    WORKDIR /work
  DOCKER
end

written = Parsers::COMBOS.map do |id, combo|
  path = File.join(HERE, "Dockerfile.#{combo[:slug]}")
  File.write(path, dockerfile(combo))
  puts "  wrote #{File.basename(path)}  (#{id})"
  File.basename(path)
end

stale = Dir.children(HERE).grep(/\ADockerfile\./).sort - written
unless stale.empty?
  warn "\nno longer in COMBOS, delete by hand if intended:"
  stale.each { |f| warn "  docker/psych_matrix/#{f}" }
end
